//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.People = new HashSet<Person>();
        }
    
        public int acc_Id { get; set; }
        public string acc_name { get; set; }
        public decimal acc_balance { get; set; }
        public string acc_type { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
