//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostCrud.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string username { get; set; }
        public string post_desc { get; set; }
        public int likes { get; set; }
        public int dislikes { get; set; }
        public string tag { get; set; }
    }
}
